#!/usr/bin/env bash 

_file=${0##*/}
error(){ printf "\033[1;31m${_file}\033[0m: $@"; exit 1 ; }

usage=\
"
Usage: ./build.sh [ options ]
\t test  - run test cases 
\t clean - clean garbage 
\t run   - run everything 
"


if [ "$#" -eq 0 ] ; then error "${usage}" ; fi      
for argument in "$@" ; do
    case "${argument}" in
	test) paver test ; shift ;;
	clean) paver clean ; shift ;;
        run) paver; paver clean ; python3 main.py; shift ;;
	run-main) python3 main.py ; shift ;; 
	install)
	    if ! [ "$(which pip3)" = "" ] ; then
		pip3 install $(cat requirements.txt) ;
	    else
		error "install pip3 first" ;
	    fi
	    shift ;; 
    esac
done



